name: "DSLab submitter"
description: "Submits an assignment to DSLab"
inputs:
  github_token:
    description: 'Derivative token for using the GitHub REST API'
    default: '${{ github.token }}'
    required: true
  tenant : 
    description: 'DSLab tenant'
    required: true
  project : 
    description: 'DSLab project'
    required: true
  user: 
    description: 'User with permission to submit projects'
    required: true
  pass: 
    description: 'User password'
    required: true
  student:
    description: "The student doing the submission"
    required: true
runs:
  using: "composite"
  steps:
    - name: sets the path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: setups Java
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "11"
        cache: "maven"