name: "DSLab submitter"
description: "Submits an assignment to DSLab"
inputs:
  github_token:
    description: 'Derivative token for using the GitHub REST API'
    default: '${{ github.token }}'
    required: true
  tenant : 
    description: 'DSLab tenant'
    required: true
  project : 
    description: 'DSLab project'
    required: true
  user: 
    description: 'User with permission to submit projects'
    required: true
  pass: 
    description: 'User password'
    required: true
  student:
    description: "The student doing the submission"
    required: true
  repo:
    description: "The student repository"
    required: true
runs:
  using: "composite"
  steps:
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        repository: "jlcanovas/dslab-pjp"
        token: ${{ inputs.github_token }}
    - name: setups Java
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "11"
        cache: "maven"
    - name: compile with Maven
      run: mvn compile 
      shell: bash
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        token: ${{ inputs.github_token }}
        path: "tgt"
    - name: creates zip for the project
      run: zip -r pec.zip tgt/ -x "tgt/.git/*"
      shell: bash
    - name: Submits via DSLab
      run: mvn exec:java -Dexec.args="${{ inputs.tenant }} ${{ inputs.project }} ${{ inputs.user }} ${{ inputs.pass }} ${{ inputs.student }} pec.zip"
      shell: bash
    - name: removes the zip file
      run: rm -f pec.zip
      shell: bash