name: "DSLab submitter"
description: "Submits an assignment to DSLab"
inputs:
  student:
    description: "The student doing the submission"
    required: true
runs:
  using: "composite"
  steps:
    - name: setups Java
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "11"
        cache: "maven"
    - name: compile with Maven
      run: mvn compile --file ${GITHUB_ACTION_PATH}/pom.xml
      shell: bash
    - name: checkout student repo
      uses: actions/checkout@v3
      secrets:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: creates zip for the project
      run: zip -r pec.zip src/ 
      shell: bash
    - name: Submits via DSLab
      secrets:
        tenant : ${{ secrets.TENANT }}
        project : ${{ secrets.PROJECT }}
        user: ${{ secrets.USER }}
        pass: ${{ secrets.PASS }}
      run: mvn compile exec:java -Dexec.args="$tenant $project $user $pass ${{ inputs.student }} pec.zip"
    - name: removes the zip file
      run: rm -f pec.zip